task: detection

num_classes: 11
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: constructionsitesafety_dataset_yolo/train/images/
    ann_file: constructionsitesafety_dataset_yolo/cssd_train.json  # data2/annotations/train2.json add testset to trainset
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 16
  num_workers: 4
  drop_last: True


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: constructionsitesafety_dataset_yolo/valid/images/
    ann_file: constructionsitesafety_dataset_yolo/cssd_valid.json
    transforms:
      type: Compose
      ops: ~

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False